export const typographyKeys = {
	h1: 'h1',
	h2: 'h2',
	h3: 'h3',
	h4: 'h4',
	h5: 'h5',
	h6: 'h6',
	button: 'button',
	button1: 'button1',
	subtitle1: 'subtitle1',
	subtitle2: 'subtitle2',
	label1: 'label1',
	label2: 'label2',
	label3: 'label3',
	body1: 'body1',
	body2: 'body2',
	callout: 'callout',
	callout1: 'callout1',
	callout2: 'callout2',
	callout3: 'callout3',
} as const

export const iconKeys = {
	arrowDown: 'arrowDown',
	arrowLeftCircle: 'arrowLeftCircle',
	star: 'star',

	accept: 'accept',
	acceptTick: 'acceptTick',

	visibilityOff: 'visibilityOff',
	visibilityOn: 'visibilityOn',
	logout: 'logout',
	caretDown: 'caretDown',
	success: 'success',
	failure: 'failure',
	closeCircle: 'closeCircle',
	googleIcon: 'googleIcon',
	logoTitle: 'logoTitle',
	plus: 'plus',
	calenderIcon: 'calenderIcon',
	addIcon: 'addIcon',
}
